sudo: required
dist: trusty
install:
    - sudo apt-get install texlive-lang-czechslovak texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - sudo apt-get install chktex
language: c
script:
- make && make test
compiler:
  - clang
  - gcc
notifications:
  slack: ifj-fit:Z3qiXOvoDKzKwuTZ7sWFsLAX
